# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f')),
                ('surname', models.CharField(max_length=100, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('date_of_birth', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u0440\u0443\u043f\u043f\u044b')),
                ('description', models.CharField(max_length=100, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0433\u0440\u0443\u043f\u043f\u044b')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u0440\u0430\u0441\u0441\u044b\u043b\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='ClientMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mails', to='mailing.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u0438\u0441\u044c\u043c\u043e \u043a\u043b\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u041f\u0438\u0441\u044c\u043c\u0430 \u043a\u043b\u0438\u0435\u043d\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings', to='mailing.ClientGroup', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=150, verbose_name='\u0422\u0435\u043c\u0430')),
                ('html_template', models.TextField(max_length=1000, verbose_name='HTML-\u0448\u0430\u0431\u043b\u043e\u043d \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('mail_from', models.EmailField(default='1@ya.ru', max_length=254, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='mailing.ClientGroup', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u043f\u0438\u0441\u044c\u043c\u0430',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u043f\u0438\u0441\u0435\u043c',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailing.MailTemplate', verbose_name='\u041f\u0438\u0441\u044c\u043c\u043e'),
        ),
        migrations.AddField(
            model_name='clientmail',
            name='mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mails', to='mailing.MailTemplate', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d \u043f\u0438\u0441\u044c\u043c\u0430'),
        ),
        migrations.AddField(
            model_name='clientmail',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mails', to='mailing.Mailing', verbose_name='\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='mailing.ClientGroup', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
